### ISSUE TITLE
[QUESTION / LOGIN] Players ignore Epic Games connections

### ISSUE THREAD

**Issue by MessireVince** [YoYoGames/GMEXT-EpicOnlineServices#6]
Hello,

After having successfully integrated the EOS extension in our game, and published it on the Epic Games Store, it appears that a great majority of  players don't authenticate in Epic, as it is an optionnal feature (you juste have to close the Epic popup login). We did add an option to recall it in case of a misclick, but still, players don't seem to use it, as we tracked so far so few achievements unlocking (and we know that players use our game enough to unlock the first achievement, we found youtube reviews in which we can see it)

I can understand that it may be feel strange for players to authenticate again, as they launch the game from the Epic Game Store in which they are already authenticated, so my question is : did we miss something in the integration ? Is there a way to catch the player profile directly from the store so they don't have to authenticate at first launch ? (FYI, for those who authenticate, next game session is ok, persistent auth is working perfectly, they don't have to re-authenticate)

"Setup Guide" section in documentation states "The Epic Launcher App needs to be installed , running and with an account logged in", but I didn't feel a real effect about it has to be "running"... or does it just mean "working correctly if you launch it" but not specially running while you launch the game ?

I also read in a closed issue that "The popup you encountered, requesting login credentials for the Epic account, is a normal and expected behavior even if you are already logged into the Epic Games Launcher or the web client.", so it seems like there is no other way, but since it's not clearly stated in the documentation...

IDE Version: 2023.8.2.108
Current Runtime: 2023.8.2.152
EOS extension: 1.4.1
EOS SDK: 1.15.4

**Comment by DiasFranciscoA** [comment]
Please refer to the official documentation when it comes to authentication since it might be subject to changes:

[EOS Auth Interface](https://dev.epicgames.com/docs/epic-account-services/auth/auth-interface)

you can use a login type of `EpicGames_LCT_ExchangeCode` as suggested bellow:

<img width="567" alt="image" src="https://github.com/YoYoGames/GMEXT-EpicOnlineServices/assets/85873067/e3692ec0-b863-48ff-b84a-7a6b6f062567">

you can get the token from the arguments passed to the game executable. You are required to use:

* `parameter_count()`
* `parameter_string(x)`

to parse the argument string and get the exchange code necessary to auto login.
